config/routes.rb
Rails.application.routes.draw do
  root "homepages#index"

  resources :contents do
    resources :comments, only: [:new, :create, :index, :show]
    member do
    end
  end
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :content
  scope :reversed, -> { order 'created_at DESC' }
end

app/models/content.rb
class Content < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  validates :title, presence: true
  scope :reversed, -> { order 'created_at DESC' }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :contents
  has_many :comments

  def password
    @_password ||= BCrypt::Password.new(password_hash)
  end

  def password=(unhashed_password)
    @_password = BCrypt::Password.create(unhashed_password)
    self.password_hash = @_password
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user
  def current_user
    User.find_by(id: session["current_user_id"])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @comments = Comment.where(content_id: params["content_id"])
    render :index
  end

  def new
    @content = Content.find_by(id: params["content_id"])
    @comment = Comment.new(user_id: current_user.id, content_id: @content.id)
  end

  def create
    @content = Content.find_by(id: params["content_id"])
    @comment = Comment.new(comment_params)

    if @comment.save
      redirect_to content_comments_path
    else
      render :new
    end
  end

  def comment_params
    params.require(:comment).permit(:user_id, :content_id, :user_comment)
  end
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  def index
    @contents = Content.all
    render :index
  end

  def new
    @content = Content.new(user_id: current_user.id)
  end

  def create
    @content = Content.new(content_params)

    if @content.save
      redirect_to contents_path
    else
      render :new
    end
  end

  def content_params
    params.require(:content).permit(:title, :label_type, :description, :user_id)
  end
end

app/controllers/homepages_controller.rb
class HomepagesController < ApplicationController
  layout "home"
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  layout "home"

  def new
  end

  def create
    @user = User.find_by(email: params[:email])

    if @user && @user.password == params[:password]
      # Does the logging in
      session["current_user_id"] = @user.id

      redirect_to contents_path
    else
      @message = "Go AWAY!"
      render :new
    end
  end

  def destroy
    session.delete("current_user_id")
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout "home"

  def new
    @user = User.new()
  end

  def create
    @user = User.new(user_params)
    session["message"] = "you signed up!"
    if @user.save
      redirect_to new_session_path
    else
      render :new
    end
  end

  def user_params
    params.require(:user).permit(:email, :full_name, :password)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/homepages_helper.rb
module HomepagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/index.html.erb
<h2>Comments for: </h2>
<h2>An original concept</h2>

<%= link_to "Home Page", contents_path %>

<% @comments.each do |comment| %>
  <h4>
    <%= comment.user.full_name %>
  </h4>
  <p>
    <%= comment.created_at%>
  </p>
  <p>
    <%= comment.user_comment %>
  </p>
<% end %>

app/views/comments/new.html.erb
<h1>New Comment for </h1>

<%= link_to "Home Page", contents_path %>

<% @comment.errors.full_messages.each do |error| %>
  <%= error %>
<% end %>

<%= form_for ([@content, @comment]) do |f| %>

  <%= f.label :user_comment %>
  <%= f.text_field :user_comment,  class: 'form-control' %>

  <%= f.hidden_field :user_id,  class: 'form-control' %>
  <%= f.hidden_field :content_id,  class: 'form-control' %>

  <%= f.submit class: "btn btn-primary"%>

<% end %>

app/views/contents/index.html.erb
<h1>Forgeddit</h1>
<h2>An original concept</h2>

<%= link_to "Add New Content to Forgeddit", new_content_path %>

<% @contents.each do |content| %>
  <h4>
    <%= link_to content.title, content.label_type %>
  </h4>
  <p>
    <%= content.label_type %>
    <%= content.description %>
    <%= content.user.full_name %>
  </p>
  <p>
     <%= content.comments.count %>
    <%= link_to " Comments", content_comments_path(content.id) %>
  </p>
  <p>
    <%= link_to "Add a Comment", new_content_comment_path(content.id) %>
  </p>
<% end %>

<br>
<p>Find me in app/views/contents/index.html.erb</p>

app/views/contents/new.html.erb
<h1>New Content Input</h1>

<%= link_to "Home Page", contents_path %>

<% @content.errors.full_messages.each do |error| %>
  <%= error %>
<% end %>

<%= form_for @content do |f| %>

  <%= f.label :title %>
  <%= f.text_field :title,  class: 'form-control' %>

  <%= f.label "Enter url link" %>
  <%= f.url_field :label_type,  class: 'form-control' %>

  <%= f.label :description %>
  <%= f.text_field :description,  class: 'form-control' %>

  <%= f.hidden_field :user_id,  class: 'form-control' %>

  <%= f.submit class: "btn btn-primary"%>

<% end %>

app/views/homepages/index.html.erb
<body>

  <div class="container">
      <ul class="nav navbar-nav">
          <li><%= link_to "Log In", new_session_path %></li>
          <li><%= link_to "Sign Up!", new_user_path %></li>
      </ul>
  </div>

</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Forgeddit</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </head>

  <body>
    <div class="container">
      <nav class='navbar navbar-default'>
        <ul class="nav navbar-nav">
          <% if current_user %>
            <p class="navbar-text navbar-right">Signed in as <%= current_user.full_name %></p>
            <li><%= link_to "Log out", session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Log in", new_session_path %></li>

          <% end %>
        </ul>
      </nav>
      <%= yield %>
    </div>

  </body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Forgeddit</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </head>

  <body>

      <%= yield %>

  </body>
</html>

app/views/users/new.html.erb
<h1>Sign up!</h1>

<%= form_for @user do |f| %>

<%= f.label :full_name %>
<%= f.text_field :full_name, class: 'form-control' %>

<%= f.label :email %>
<%= f.text_field :email, class: 'form-control' %>

<%= f.label :password %>
<%= f.password_field :password, class: 'form-control' %>

<hr>

<%= f.submit class: 'btn btn-primary' %>
<% end %>

<br>

<p>
  <%= link_to "Welcome Page", root_path %>
</p>